// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudcgGldY_iU7n8ALAQ6o0mdc8DVBB4lM',
    appId: '1:218608967981:web:9612abbb55dac64d6b33a4',
    messagingSenderId: '218608967981',
    projectId: 'instagram-clone-a27db',
    authDomain: 'instagram-clone-a27db.firebaseapp.com',
    storageBucket: 'instagram-clone-a27db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAm1GnkaKegv7QvjM5gjqlOZ_aasRXH0U',
    appId: '1:218608967981:android:382fcad9c0e21f306b33a4',
    messagingSenderId: '218608967981',
    projectId: 'instagram-clone-a27db',
    storageBucket: 'instagram-clone-a27db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzdXDARhte56h32djh_qG9cEjB79M4Nk',
    appId: '1:218608967981:ios:331bead61e7472456b33a4',
    messagingSenderId: '218608967981',
    projectId: 'instagram-clone-a27db',
    storageBucket: 'instagram-clone-a27db.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQzdXDARhte56h32djh_qG9cEjB79M4Nk',
    appId: '1:218608967981:ios:670c6938875736e06b33a4',
    messagingSenderId: '218608967981',
    projectId: 'instagram-clone-a27db',
    storageBucket: 'instagram-clone-a27db.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
